[build-system]
requires = ["setuptools","wheel"]
build-backend= "setuptools.build_meta"

[project]
name = "module-web-pentest-kalia"
version = "1.0.0"
description = "Independent web module extracted from Kalia"
authors = [{ name = "Stéphane Kamwa"}]
dependencies = ["beautifulsoup4","dnspython","pymetasploit3","python-dotenv","Requests","shodan"]